<div>
<table style="width: 100%">
	<tr>
		<td>
		<table style="width: 100%">
			<tr>
                <td ><center><font size="5"><b>Module 49</b></font><center>
                <center><font size="6">Digital Innovations for Water Challenges</font><center></td>
			</tr>
			<tr>
                <td><center><font size="14">Notebook 1c</font><center></td>
			</tr>
			<tr>
                <td><center><font size="6"><b>Read Excel or CSV files to Python</b></font><center></td>
			</tr>
		</table>
		</td>
		<td><center><img src='images\ihe-delft-institute_unesco_fc-lr.jpg'></img></td>
	</tr>
</table>
</div>

# Table of contents
1. [Learning objectives](#learningobs)
2. [Introduction to Pandas read file](#introduction)
3. [An example](#Example)

# 1. Learning objectives<a name="learningobs"></a>

- Understand how to read Excel and CSV files in to Python.
- Use Pandas to read Excel and CSV files and do some computation and write the results to file.


# 2. Introduction<a name="introduction"></a>

Tabular data can be stored in different file types such as excel and csv. Reading such files in python is easier using the Pandas library. Pandas modules <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html">read_excel()</a>  and <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html">read_csv()</a> are used to read tabular data from excel and csv files respectively.

The pandas module read_excel() function can be used to read the excel file data into a DataFrame object. If you look at an excel sheet, it’s a two-dimensional table. The DataFrame object also represents a two-dimensional tabular data structure. 

CSV files are used a lot in storing tabular data into a file. We can easily export data from database tables or excel files to CSV files. Similarly as excel, the pandas module read_csv() function can be used to read the csv file data into a DataFrame object.

Once the files are read to a Pandas’ object, Pandas offers many types of inbuilt data manipulation and you can also write the results back as excel or csv files.

<figure>
<img src="./data_files/dataframe.png" style="width:40%">
<figcaption align = "center"> DataFrame </figcaption>
</figure>

## 3 - An example <a name="Example"></a>
### 3.1 - Read Excel file
- Pandas read_excel() function reads the excel sheet data into a DataFrame object.
- An excel sheet is a two-dimensional table and the DataFrame object represents the two-dimensional tabular view.
- The Pandas read_excel() function has a lot of different parameters. Some of the main parameters are described in the table below. The full list can be found in the <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html">official documentation</a>.

Parameter       |    Description                                   |    Available Option
----------------|--------------------------------------------------|--------------------------
io| The string path to the workbook.| URL to file, path to file, etc.
sheet_name      | The name of the sheet to read. Will default to the first sheet in the workbook (position 0)| The string path to the workbook 
usecols| The columns to read, if not all columns are to be read| Can be strings of columns, Excel-style columns (A:C), or integers representing positions columns
dtype| The datatypes to use for each column| Dictionary with columns as keys and data types as values
skiprows| The number of rows to skip from the top| Integer value representing the number of rows to skip
nrows| The number of rows to parse| Integer value representing the number of rows to read
                

To read an excel file, the path to the file should be provided. The path can be  a path to local file ot a to URL.

In [1]:
# Read excel file
import pandas as pd
file_path = r'./data_files/Flowbru_Pluvio_VALI_2019.xlsx'
df = pd.read_excel(file_path)
df.head() # to print the first five rows of the dataframe

,date/time,Pluv. Avant-Port[mm],Pluvio Ganshoren[mm],Pluvio Roodebeek[mm],Pluvio Hippocrat[mm],Pluvio Ecluse[mm],Pluvio Paelinckx[mm],Pluv. Kinsendael[mm],Pluviometre[mm],Pluv. Dépôt Co[mm],Pluvio Voets[mm],Pluvio IRM[mm],Pluvio Flagey[mm],Pluv. Ste Gudule[mm],Pluvio Bemel[mm],Pluvio Broekbeek[mm],Pluvio Nord[mm]
0,2019-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2019-01-01 00:05:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2019-01-01 00:10:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2019-01-01 00:15:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2019-01-01 00:20:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

The file has two sheets. So, how does Pandas know which sheet to load? By default, Pandas will use the first sheet (positionally), unless otherwise specified.
<div class="alert alert-success">

**EXERCISE 1**:

* Read the `the second sheet` of the file.

<details>
  <summary>Hints</summary>

* Specify sheet_name.

</details>
    
</div>

In [2]:
#Enter your answer code in this cell

#### How to Specify Columns Names in pd.read_excel().

In some cases there is no need to load every column from an excel sheet, you can use the *usecols* parameter. 
For this parameter you can specify:
- A list of column names,
- A string of Excel column ranges,
- A list of integers specifying the column indices to load


<div class="alert alert-success">

**EXERCISE 2**:

* Read the columns `Pluv. Avant-Port[mm]` and `Pluvio Voets[mm]` from the first sheet.

<details>
  <summary>Hints</summary>

* Specify sheet_name and usecols

</details>
    
</div>

In [ ]:
#Enter your answer code in this cell

#### How to Skip Rows When Reading Excel Files in Pandas
In some cases, you may encounter files where there are formatted title rows in your Excel file. in these cases, it is possible to skip a certain number of rows when reading an Excel file. 
This can be done using the *skiprows* parameter. 


<div class="alert alert-success">

**EXERCISE 3**:

* Skip the header row from you excel file.

<details>
  <summary>Hints</summary>

* Use skiprows parameter and specify the number of rows you want to skip.

</details>
    
</div>

In [ ]:
#Enter your answer code in this cell

#### How to Read Multiple Sheets in an Excel File in Pandas
You can read multiple sheets at the same time. This can be done using the *sheet_name* parameter. <br>
You can  pass in a list of sheets to read multiple sheets at once to the *sheet_name* parameter.


<div class="alert alert-success">

**EXERCISE 4**:

* Read the two sheets in your excel file.

<details>
  <summary>Hints</summary>

* Use sheet_name parameter and specify the name of the sheets you want to read.

</details>
    
</div>

In [ ]:
#Enter your answer code in this cell

### 3.2 - Read csv file
- Pandas read_csv() function reads csv files into a Dataframe object.
- CSV (coma separted values) files are frequently used to store tabular data into a file. Data from database tables or excel files can be exported to CSV files.
- The Pandas read_csv() function has many different parameters. Some of the main parameters are described in the table below. The full list can be found in the <a href= "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html">official documentation</a>.

Parameter       |    Description                                   
----------------|--------------------------------------------------
filepath_or_buffer| It is the location of the file which is to be retrieved using this function It accepts any string path or URL of the file.
sep| It stands for separator| default is ‘, ‘ as in CSV(comma separated values) but other separators are also possible.
header| It accepts int, a list of int, row numbers to use as the column names, and the start of the data. If no names are passed, i.e., header=None, then,  it will display the first column as 0, the second as 1, and so on.
usecols| It is used to retrieve only selected columns from the CSV file.
nrows| It means a number of rows to be displayed from the dataset.
index_col| If None, there are no index numbers displayed along with records.  
skiprows| Skips passed rows in the new data frame.



To read an excel file, the path to the file should be provided. The path can be  a path to local file or to a URL.

In [3]:
# Read csv file
file_path = r'./data_files/Flowbru_Pluvio_VALI_2019.csv'
df = pd.read_csv(file_path, sep = ',')
df.head()

,Unnamed: 0,date/time,Pluv. Avant-Port[mm],Pluvio Ganshoren[mm],Pluvio Roodebeek[mm],Pluvio Hippocrat[mm],Pluvio Ecluse[mm],Pluvio Paelinckx[mm],Pluv. Kinsendael[mm],Pluviometre[mm],Pluv. Dépôt Co[mm],Pluvio Voets[mm],Pluvio IRM[mm],Pluvio Flagey[mm],Pluv. Ste Gudule[mm],Pluvio Bemel[mm],Pluvio Broekbeek[mm],Pluvio Nord[mm]
0,0,2019-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,2019-01-01 00:05:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,2019-01-01 00:10:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,2019-01-01 00:15:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,2019-01-01 00:20:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

#### How to Specify Columns Names in pd.read_csv().

In cases there is no need to load every column from a csv file, you can use the *usecols* parameter. 
For this parameter you can specify:
- A list of column names,
- A list of integers specifying the column indices to load


<div class="alert alert-success">

**EXERCISE 5**:
   
* Read the columns `Pluvio Hippocrat[mm]`, `Pluvio Broekbeek[mm]` and `Pluvio Voets[mm]` from the csv file.

<details>
  <summary>Hints</summary>

* Specify column names or thier indices for the usecols paramater

</details>
    
</div>

In [ ]:
#Enter your answer code in this cell

#### How to Skip Rows When Reading CSV Files in Pandas
As in the case in excel files, you can also skip rows in reading csv filess using the *skiprows* parameter. 

<div class="alert alert-success">

**EXERCISE 6**:

* Skip the header row from you csv file.

<details>
  <summary>Hints</summary>

* Use skiprows parameter and specify the number of rows you want to skip.

</details>
    
</div>

In [ ]:
#Enter your answer code in this cell